### ISSUE TITLE
Check if we can inherit from IPS TobaccoUse

### ISSUE THREAD

**Issue by alexanderkiel** [samply/bbmri-fhir-ig#77]
Is there a reason why we don't inherit from [IPS TobaccoUse](http://hl7.org/fhir/uv/ips/2019Sep/StructureDefinition-Observation-tobaccouse-uv-ips.html). Perhaps it don's have any value, because we had to override the profile and subject reference URL's. At least we should mention that we are fully compatible with that profile.

**Comment by noemide** [comment]
I believe my reasoning was that our "Patient" is not nescessarily an "IPSPatient" and the IPS profile reqires its subject to be one. But we should mention the compatibility in the Oberservation itself.
