### ISSUE TITLE
Revise Biobank.contact.address being 1:1

### ISSUE THREAD

**Issue by alexanderkiel** [samply/bbmri-fhir-ig#83]

**Comment by noemide** [comment]
See issue #81 - this is based on the BBMRI Directory requirements.

**Comment by noemide** [comment]
Ok, these requirements are "hard" requirements - data sets without them will not be accepted by the directory, if there is no default value. I suggest to close this ticket and open a new one for further investigating the default vlues and adding them to the profiles where possible.

**Comment by alexanderkiel** [comment]
Can we add default values to profiles?

**Comment by noemide** [comment]
OK, default values are only allowed in logical models. So we need this field to be filled for the directory to work. Out of all the addres attributes, only country need to be filled, the rest is optional. We could do something in the directory-sync module and try to guess the country from the bbmri-ID, but i believe that the biobanks should be able to fill out this single field (which probably will not change over time).

**Comment by alexanderkiel** [comment]
After all your information, I think we should keep it 1:1.
